# Do not edit this file.

import solution, sqlite3, sys

def db2Dict(inDb): #converts a database to a dictionary of relations
    conn = sqlite3.connect(inDb); cur = conn.cursor()
    cur.execute("SELECT name FROM sqlite_master WHERE type='table';") # Get table names
    tables = [row[0] for row in cur.fetchall()]
    dbDict = {}
    for table in tables:
        cur.execute(f"SELECT * FROM {table};")
        dbDict[table] = set(cur.fetchall())
    conn.close()
    return dbDict

rels=db2Dict(sys.argv[1]); res=solution.task0(rels)
for msg in res: print(msg)

if len(sys.argv)>2: #task1
	outDb=sys.argv[2];
	conn = sqlite3.connect(outDb); cursor = conn.cursor()
	for sqlStatement in solution.task1(): cursor.execute(sqlStatement);
	conn.commit(); conn.close()


""""




"""